### signup a user
POST http://localhost:3000/auth/signup
Content-Type: application/json
Credentials: include

  {
    "email": "user@ee",
    "password": "user"
  }

### login a user
POST http://localhost:3000/auth/login
Content-Type: application/json
Credentials: include

  {
    "email": "user@ee",
    "password": "user"
  }

###  Authinticate a user, this will not work for you unless you replace the token with one created for your user
GET http://localhost:3000/auth/authenticate
Credentials: include

